### PR TITLE
dx12: Fix tier1 resource creation

### LINKED ISSUE #1756: hal: dx12 startup crash
When I try running the quad example using the dx12 backend on my Windows machine with a GTX560 Ti, it crashes during startup.

dx12 debug runtime log attached.

[quad-dx12-rhuagh.LOG](https://github.com/gfx-rs/gfx/files/1653359/quad-dx12-rhuagh.LOG)

### PR DESCRIPTION
**Pull request by msiglreith**
Tier1 devices expose 3 memory type groups (buffer only, image only and target only). We can only create a buffer for mapping in the first group. This PR fixes the exposed memory types and only creates buffers if possible (tier2 or tier1 buffer only and cpu visible).

The remaining issue are exposed image memory types, which should be only device local for tier1 (will be addressed in a followup). Vulkan requires us to expose at least one host-visible memory type for images supporting linear tiling. But we can circumvent this by not exposing any format supporting linear tiling at all for heap tier1 hardware..

Fixes #1756 
cc @Rhuagh @AlphaModder 

NOTE: This PR is written against the generic range type PR.

### CODE REVIEW

File: src/backend/dx12/src/lib.rs [hunk 1]
```diff
@@ -709,8 +709,20 @@ impl hal::Instance for Instance {
...
-                    types.extend(base_memory_types.iter());
+                for i in 0..4 {
+                    types.extend(base_memory_types
+                        .iter()
+                        .map(|mem_type| {
+                            let mut ty = mem_type.clone();
+
+                            // Images and RenderTargets are not host visible as we can't create
+                            // a corresponding buffer for mapping
+                            if i >= 2 {
```
Comment (kvark) [inline src/backend/dx12/src/lib.rs]: we should get rid of those magic constants eventually

**Comment by Rhuagh** [comment]
LGTM!

**Comment by msiglreith** [comment]
@Rhuagh Thanks for testing!
@kvark Addressed that magic values, should be cleaner now

just waiting on CI now (:

**Comment by msiglreith** [comment]
@kvark done
