### PR TITLE
[0.5/dx12] essential fixes to depth views and command allocation

### LINKED ISSUE #2656: [dx12] wgpu-rs cube validation errors
Short info header:
- GFX version: 0.1
- OS: Windows 10

```
D3D12 WARNING: ID3D12Device::CreateConstantBufferView: Resource 0x0000019FAA88D1F0:'Unnamed ID3D12Resource Object' and 1 other resources contain the GPU Virtual Address range [0xffffb80203860000, 0xffffb802038600ff] on a Heap (0x0000019F9B41C050:'Unnamed ID3D12Heap Object').  This may be OK as long as all of these resources are in the same state however developer probably did not intend to make use of this behavior. [ STATE_CREATION WARNING #926: HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS]
D3D12 WARNING: ID3D12CommandList::IASetIndexBuffer: Resource 0x0000019FAA88AE80:'Unnamed ID3D12Resource Object' and 1 other resources contain the GPU Virtual Address range [0xffffb80202c60000, 0xffffb80202c60047] on a Heap (0x0000019F9B41B330:'Unnamed ID3D12Heap Object').  This may be OK as long as all of these resources are in the same state however developer probably did not intend to make use of this behavior. [ STATE_CREATION WARNING #926: HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS]
D3D12 WARNING: ID3D12CommandList::IASetVertexBuffers: Resource 0x0000019FB8304270:'Unnamed ID3D12Resource Object' and 1 other resources contain the GPU Virtual Address range [0xffffb80202860000, 0xffffb8020286023f] on a Heap (0x0000019F9B41B090:'Unnamed ID3D12Heap Object').  This may be OK as long as all of these resources are in the same state however developer probably did not intend to make use of this behavior. [ STATE_CREATION WARNING #926: HEAP_ADDRESS_RANGE_INTERSECTS_MULTIPLE_BUFFERS]
D3D12 ERROR: ID3D12GraphicsCommandList::Reset: Reset fails because the command list was not closed. [ EXECUTION ERROR #544: COMMAND_LIST_OPEN]
```

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2656
Tested on vange-rs and wgpu-rs examples
With these fixes, we run wgpu-rs stuff without validation errors, and terminate successfully :tada:

### CODE REVIEW

File: src/backend/dx12/src/device.rs [hunk 1]
```diff
@@ -2656,24 +2648,45 @@ impl d::Device<B> for Device {
...
             {
-                self.view_image_as_shader_resource(info.clone()).ok()
+                let info = if info.range.aspects.contains(format::Aspects::DEPTH) {
+                    conv::map_format_shader_depth(surface_format)
+                        .map(|format| ViewInfo {
+                            format,
+                            .. info.clone()
+                        })
+                } else if info.range.aspects.contains(format::Aspects::STENCIL) {
+                    let new_swizzle = conv::swizzle_rg(swizzle);
```
Comment (msiglreith) [inline src/backend/dx12/src/device.rs:2658]: could you add a comment why this is needed? I guess dx12 maps stencil to the R channel here compared to Vulkan?

Comment (kvark) [reply src/backend/dx12/src/device.rs:2658]: it's the opposite: dx12 maps it to G, while Vulkan expects R

Comment (kvark) [reply src/backend/dx12/src/device.rs:2660]: anyway, added a small comment now

**Comment by kvark** [comment]
Thanks for the review!
bors r=msiglreith
