### PR TITLE
[mtl] unflatten descriptor pools

### LINKED ISSUE #2383: Metal descriptor pools don't take shader stages into account
It appears that with #2300 we no longer know ahead of time how many descriptors are needed. The pool creation isn't receiving any information about shader stages, so we can't duplicate each entry properly per stage... As a result, some of the CTS sections (in specialization constants, see #2381) fail because they can't allocate sufficient number of descriptors.

There are two ways to address this:
  1. as a hack, just multiply the count by 2. This would work for descriptors that are either used in graphics or compute, but not in both.
  2. revert #2300 logic in some way, or at least re-think the layout of descriptor pools

### PR DESCRIPTION
**Pull request by kvark**
Partially reverts #2300
Fixes #2383

PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds
- [x] tested examples with the following backends: metal
- [ ] `rustfmt` run on changed code

Tested on Dota2 and some CTS categories.

### CODE REVIEW

File: src/backend/metal/src/native.rs [hunk 1]
```diff
@@ -159,6 +159,12 @@ impl<T> ResourceData<T> {
             samplers: fun(&self.samplers),
         }
     }
+
+    pub fn consume<V, F: FnMut(&mut T, V)>(&mut self, other: ResourceData<V>, mut fun: F) {
```
Comment (grovesNL) [inline src/backend/metal/src/native.rs]: This is always passed the same function, could we just put the logic here instead?

**Comment by kvark** [comment]
Thanks for the review! `consume` is fixed now
bors r=grovesNL
