### PR TITLE
[GL] Add empty fragment shader when only vertex shader present

### LINKED ISSUE #3562: gfx_backend_gl: Shader compilation error: illegal use of reserved word 'readonly'
Short info header:
- GFX version: 0244e3401e9f127617cb8636397048584e7bfe8a (as depended upon by wgpu-rs 89175e19c1ca37707be9c24f6c83adde5b2c351 )
- OS: Fedora 33 (Linux 5.9.14-200.fc33.x86_64)
- GPU: Radeon RX 580

I am once again trying to run Ruffle with the OpenGL backend. On startup I get this error:

```
[2021-01-04T15:51:14Z DEBUG gfx_backend_gl::device] SPIR-V options CompilerOptions { version: V3_00Es, force_temporary: false, vulkan_seman
tics: false, separate_shader_objects: false, flatten_multidimensional_arrays: false, enable_420_pack_extension: true, emit_push_constant_as
_uniform_buffer: false, emit_uniform_buffer_as_plain_uniforms: false, emit_line_directives: false, enable_storage_image_qualifier_deduction
: true, force_zero_initialized_variables: true, vertex: CompilerVertexOptions { invert_y: false, transform_clip_space: false, support_nonze
ro_base_instance: true }, fragment: CompilerFragmentOptions { default_float_precision: Medium, default_int_precision: High }, entry_point: 
Some(("main", Fragment)) }
[2021-01-04T15:51:14Z DEBUG gfx_backend_gl::device] SPIRV-Cross generated shader: <see gist>
```
 https://gist.github.com/torokati44/a0404ee80f99645fe2242a00a68b97ec
 ```
[2021-01-04T15:51:14Z INFO  gfx_backend_gl::device]     Compiled shader 27
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationFailed("0:5(16): error: illegal use of reserved word `readonly\'\n0:5(16): error: syntax error, unexpected ERROR_TOK\n")', /home/attila/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/0244e34/src/backend/gl/src/device.rs:560:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: gfx_backend_gl::device::Device::compile_shader
   4: gfx_backend_gl::device::Device::create_shader_program
   5: <gfx_backend_gl::device::Device as gfx_hal::device::Device<gfx_backend_gl::Backend>>::create_graphics_pipeline
   6: wgpu_core::device::Device<B>::create_render_pipeline
   7: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_render_pipeline
   8: <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline
   9: wgpu::Device::create_render_pipeline
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

Running with the Vulkan backend works flawlessly.

### LINKED ISSUE #3580: [GL] Panic with missing fragment shader
Short info header:
- GFX version:  master/49d2cefdbbc94dcd4d2abf212904ce1addab0f55
- OS: Android
- GPU: Mali-T830

Use case: [wgpu-rs shadow example](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/shadow).

```text
2021-01-12 01:58:20.891 32464-32491/rust.example.shadow D/gfx_backend_gl::device: SPIR-V options CompilerOptions { version: V3_00Es, force_temporary: false, vulkan_semantics: false, separate_shader_objects: false, flatten_multidimensional_arrays: false, enable_420_pack_extension: true, emit_push_constant_as_uniform_buffer: false, emit_uniform_buffer_as_plain_uniforms: false, emit_line_directives: false, enable_storage_image_qualifier_deduction: true, force_zero_initialized_variables: true, vertex: CompilerVertexOptions { invert_y: false, transform_clip_space: false, support_nonzero_base_instance: true }, fragment: CompilerFragmentOptions { default_float_precision: Medium, default_int_precision: High }, entry_point: Some(("main", Vertex)) }
2021-01-12 01:58:20.894 32464-32491/rust.example.shadow D/gfx_backend_gl::device: SPIRV-Cross generated shader:
    #version 300 es
    
    layout(std140) uniform Globals
    {
        mat4 u_ViewProj;
    } _19;
    
    layout(std140) uniform Entity
    {
        mat4 u_World;
        vec4 u_Color;
    } _25;
    
    layout(location = 0) in ivec4 a_Pos;
    
    void main()
    {
        gl_Position = (_19.u_ViewProj * _25.u_World) * vec4(a_Pos);
    }
2021-01-12 01:58:20.896 825-5882/? D/WindowManager: finishDrawingWindow: Window{b36b88 u0 StatusBar} mDrawState=READY_TO_SHOW
2021-01-12 01:58:20.898 32464-32491/rust.example.shadow I/gfx_backend_gl::device: 	Compiled shader 2
2021-01-12 01:58:20.898 32464-32491/rust.example.shadow I/gfx_backend_gl::device: 	Linked program 1
2021-01-12 01:58:20.898 32464-32491/rust.example.shadow E/gfx_backend_gl::device: 	Log: Link failed because of missing fragment shader.
2021-01-12 01:58:20.899 32464-32490/rust.example.shadow I/RustStdoutStderr: thread '<unnamed>' panicked at 'failed to create graphics pipeline: Implementation specific error occurred', /Users/indish/Dev/RustProjects/wgpu/wgpu-core/src/device/mod.rs:2207:26
```

Any ideas how we can fix it? Can we just add empty fragment shader when only vertex shader present?

```glsl
#version 300 es
void main(void) {}
```

### PR DESCRIPTION
**Pull request by Gordon-F**
Fixes #3580
Possible fixes #3562
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends: OpenGL ES

### CODE REVIEW

File: src/backend/gl/src/device.rs [hunk 1]
```diff
@@ -127,8 +127,19 @@ impl Device {
         let mut name_binding_map = FastHashMap::<String, (n::BindingRegister, u8)>::default();
         let mut sampler_map = [None; MAX_TEXTURE_SLOTS];
 
+        let mut is_fragment_stage_exists = false;
+        let mut is_vertex_stage_exists = false;
```
Comment (kvark) [inline src/backend/gl/src/device.rs:131]: vertex stage is not optional, it has to exist

File: src/backend/gl/src/device.rs [hunk 2]
```diff
@@ -290,9 +324,11 @@ impl Device {
         let version = self.share.info.shading_language.tuple();
         compile_options.version = if is_embedded {
             match version {
-                (3, 00) => glsl::Version::V3_00Es,
+                (3, 20) | (3, 2) => glsl::Version::V3_20Es,
```
Comment (kvark) [inline src/backend/gl/src/device.rs:327]: does this require a new spirv_cross?
@grovesNL could we get it on crates, please?

**Review by kvark — APPROVED** [review]

File: src/backend/gl/src/device.rs (hunk 2 above)
Comment (Gordon-F) [reply src/backend/gl/src/device.rs:322]: My bad. Forgot about `cargo update`. 0.22.2 already released. Ready to merge.

Comment (kvark) [reply src/backend/gl/src/device.rs:322]: so now the backend requires `0.22.2`, we need to express this in the Cargo manifest accordingly

**Review by kvark — CHANGES_REQUESTED** [review]
last minor note about spirv-cross dependency

File: src/backend/gl/src/device.rs (hunk 2 above)
Comment (Gordon-F) [reply src/backend/gl/src/device.rs:322]: You mean exactly `0.22.2` ?

We already set `0.22` in Cargo manifest.

```toml
spirv_cross = { version = "0.22", features = ["glsl"]}
```

Comment (kvark) [reply src/backend/gl/src/device.rs:322]: right, with your PR it should now be "0.22.2", so that people don't get the breakage when they update.

File: src/backend/dx11/Cargo.toml [hunk 3]
```diff
@@ -27,7 +27,7 @@ bitflags = "1"
 libloading = "0.6"
 log = { version = "0.4" }
 smallvec = "1.0"
-spirv_cross = { version = "0.22", features = ["hlsl"] }
+spirv_cross = { version = "0.22.2", features = ["hlsl"] }
```
Comment (kvark) [inline src/backend/dx11/Cargo.toml:30]: why are we changing the version everywhere? we only require `0.22.2` in the GL backend, no need to touch the other manifests

Comment (Gordon-F) [reply src/backend/dx11/Cargo.toml]: Sorry, misunderstood you. Fixed.

**Comment by Gordon-F** [comment]
With all the latest GL backed changes wgpu shadow example at least don't panic on device :smile:

gl_shadow

**Review by kvark — APPROVED** [review]
Great, thank you!
bors r+
