### PR TITLE
Metal mega-queue, coherent memory, and other goodies

### LINKED ISSUE #2069: Coherent memory on Metal
Here is the strategy (discussed with VkPI):
  - have one shared buffer backing a coherent memory allocation
  - represent buffers in coherent memory as just a range
  - represent textures as aliases on that memory buffer. The restrictions put in place for the mappable textures (linear tiling, 1D, no mipmaps) effectively make it compatible with buffer reinterpretation.

### LINKED ISSUE #2092: Broken depth ranges on Metal
All tests here are failing: "dEQP-VK.draw.inverted_depth_ranges". It doesn't look like Metal respects the depth viewport range as it should. I submitted a bug report, will keep this open for tracking.

### LINKED ISSUE #2094: Queue synchronization in Metal
Metal has a limit on the number of command buffers a queue can maintain in flight (default is 64). In order to support unlimited number of command buffers, we maintain a pool of queues, from which the command buffers are allocated. The question is now - do we need to have any extra synchronization between command buffers spawned by different queues?..

Example:
  - cmdbuf A is allocated from Queue 1
  - cmdbuf B is allocated from Queue 2
  - users commits A followed by B
  - user has a semaphore/fence associated with B, and upon reaching that they assume that A is done as well. Will this guaranteed to be the case on Metal?

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2069
Fixes #2094
Fixes #2092 

This PR accumulated quite a few seemingly unrelated changes, but all rather tasty ones:
  - one mega-queue instead of a queue pool
  - condvars for fences
  - enabled coherent memory
  - inverted depth range workaround
  - depth blits

PR checklist:
- [x] `make` succeeds (on *nix)
- [x] `make reftests` succeeds
- [ ] tested examples with the following backends:

### CODE REVIEW

File: src/backend/metal/src/command.rs [hunk 1]
```diff
@@ -27,50 +27,58 @@ use {conversions as conv, soft};
...
+        token.active = false;
+        self.reserve.start -= 1;
+    }
+
+    /// Block until GPU is idle.
+    pub(crate) fn wait_idle(queue: &Mutex<Self>) {
+        debug!("waiting for idle");
+        let _pool = AutoreleasePool::new();
+        // note: we deliberately don't hold the Mutex lock while waiting,
+        // since the completition handlers need to access it.
```
Comment (msiglreith) [inline src/backend/metal/src/command.rs]: typo: completion

File: src/backend/metal/src/command.rs [hunk 2]
```diff
@@ -27,50 +27,58 @@ use {conversions as conv, soft};
...
-        self.queues[index].reserve.start -= 1;
+    /// Returns a command buffer to a virtual pool.
+    pub(crate) fn release(&mut self, mut token: Token) {
+        token.active = false;
+        self.reserve.start -= 1;
+    }
+
+    /// Block until GPU is idle.
+    pub(crate) fn wait_idle(queue: &Mutex<Self>) {
+        debug!("waiting for idle");
```
Comment (msiglreith) [inline src/backend/metal/src/command.rs]: intended debug message?

File: src/backend/metal/src/command.rs [hunk 3]
```diff
@@ -1166,15 +1168,13 @@ impl CommandBuffer {
 
 impl com::RawCommandBuffer<Backend> for CommandBuffer {
     fn begin(&mut self, flags: com::CommandBufferFlags, _info: com::CommandBufferInheritanceInfo<Backend>) {
+        self.reset(false);
```
Comment (grovesNL) [inline src/backend/metal/src/command.rs]: Why didn't this fail before?

**Comment by kvark** [comment]
Thanks for the reviews!
It didn't fail because we were leaking command buffers...

Bors r=msiglreith,grovesNL

File: src/backend/metal/src/command.rs (hunk 2 above)
Comment (kvark) [reply src/backend/metal/src/command.rs]: yeah, it's been there before as well

**Comment by kvark** [comment]
Thanks!
Bors r=grovesNL
