### PR TITLE
Smaller dx12 bug fixes

### LINKED ISSUE #1957: [dx12] Copy split assert on PBR IBL sample
https://github.com/SaschaWillems/Vulkan/tree/master/examples/pbribl
The sample hits [this](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12/src/command.rs#L689) assert during copying a cube texture.

cc @kvark

### PR DESCRIPTION
**Pull request by msiglreith**
* fix SRV format for depth stencil view
* expose more format information for BC formats
* fix buffer offset for buffer to image copies (bytes vs texels)
* fix number of bytes for rgba16 formats

Fixes #1957

### CODE REVIEW

File: src/backend/dx12/src/device.rs [hunk 1]
```diff
@@ -620,8 +620,15 @@ impl Device {
     ) -> Result<d3d12::D3D12_CPU_DESCRIPTOR_HANDLE, image::ViewError> {
         #![allow(non_snake_case)]
 
+        // Depth-stencil formats can't be used for SRVs.
+        let format = match info.format {
+            dxgiformat::DXGI_FORMAT_D16_UNORM => dxgiformat::DXGI_FORMAT_R16_UNORM,
+			dxgiformat::DXGI_FORMAT_D32_FLOAT => dxgiformat::DXGI_FORMAT_R32_FLOAT,
```
Comment (kvark) [inline src/backend/dx12/src/device.rs]: whitespace is wrong

**Comment by msiglreith** [comment]
bors r=kvark
