### PR TITLE
[WIP] [DX11] fix crash when window is minimized

### LINKED ISSUE #1156: [DX11] All examples crash when window is minimized
Windows / DX11 / Gfx-0.14.0 and master branch, too.

gfx_window_dxgi::window.swap_buffers() panics at 'assertion failed: `(left == right)` (left: `0`, right: `142213121`)'. This happens when you minimize application window. Can be reproduced on every example code.

### PR DESCRIPTION
**Pull request by Androcas**
Closes #1156 

I fixed the minimization crash by ignoring `DXGI_STATUS_OCCLUDED`, so the window will be resized to (0, 0). 
I called `update_views` in gfx_app and I'm not sure if `device.clear_state()` is necessary.

### CODE REVIEW

File: src/window/dxgi/src/lib.rs [hunk 1]
```diff
@@ -178,16 +179,16 @@ pub fn init_raw(wb: winit::WindowBuilder, color_format: format::Format)
 }
 
 /// Update the internal dimensions of the main framebuffer targets. Generic version over the format.
-pub fn update_views<Cf>(window: &mut Window, factory: &mut Factory, device: &mut Device, width: u16, height: u16)
+pub fn update_views<Cf, D>(window: &mut Window, factory: &mut Factory, device: &mut D, width: u16, height: u16)
             -> Result<h::RenderTargetView<Resources, Cf>, f::TargetViewError>
-where Cf: format::RenderFormat
+where Cf: format::RenderFormat, D: core::Device
```
Comment (kvark) [inline src/window/dxgi/src/lib.rs]: why not use `Device` directly as it used to?

File: src/window/dxgi/src/lib.rs [hunk 2]
```diff
@@ -178,16 +179,16 @@ pub fn init_raw(wb: winit::WindowBuilder, color_format: format::Format)
...
 {
     use core::Device;
     
     factory.cleanup();
-    device.clear_state();
+    //device.clear_state();
```
Comment (kvark) [inline src/window/dxgi/src/lib.rs]: `clear_state` is still needed in order to really free the old back buffer

File: src/lib.rs [hunk 3]
```diff
@@ -217,8 +217,9 @@ A: Sized + ApplicationBase<gfx_device_dx11::Resources, D3D11CommandBuffer>
             }
         }
         if let Some((width, height)) = new_size {
-            device.clear_state();
-            match window.resize_swap_chain(&mut factory, width, height) {
+            println!("{:?}", (width, height));
```
Comment (kvark) [inline src/lib.rs]: temporary `println`?

**Comment by Androcas** [comment]
I used a generic to manage the two devices of DX11 (Deferred and Device)

**Comment by Androcas** [comment]
By the way, the examples are not releasing the targets so they all raise the error.

**Comment by kvark** [comment]
Thanks!
Is this still WIP?

**Comment by Androcas** [comment]
I think it's ready to be merged

**Comment by kvark** [comment]
@homu r+

**Comment by ngreduce** [comment]
Hi. When this fix will be on crates.io?
