### PR TITLE
[GL] Fix Android support

### LINKED ISSUE #3550: [GL] Android context creation failed error
Short info header:
- GFX version: master (40b6220a937a4c8663ce06aa8a7219cf131e60e2)
- OS: Android 10 (API level 29 https://github.com/timothee-haudebourg/khronos-egl/issues/11)
- GPU: Mali-G72

```
2020-12-22 13:22:08.761 2937-4293/rust.quad_android I/RustStdoutStderr: Waiting for NativeScreen
2020-12-22 13:22:08.864 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: setView = com.android.internal.policy.DecorView@5b6f8a7 TM=true MM=false
2020-12-22 13:22:08.926 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: Relayout returned: old=(0,0,1200,2000) new=(0,0,1200,2000) req=(1200,2000)0 dur=25 res=0x7 s={true 526057046016} ch=true
2020-12-22 13:22:08.936 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: ViewRootImpl >> surfaceCreated
2020-12-22 13:22:08.936 2937-4293/rust.quad_android I/RustStdoutStderr: NativeScreen Found:RwLockReadGuard { lock: RwLock { data: Some(NativeWindow { ptr: 0x7a7b718010 }) } }
2020-12-22 13:22:08.938 2937-4294/rust.quad_android I/gfx_backend_gl::windo..: Client extensions: "EGL_EXT_client_extensions EGL_KHR_platform_android EGL_ANGLE_platform_angle EGL_ANDROID_GLES_layers"
2020-12-22 13:22:08.938 2937-4294/rust.quad_android I/gfx_backend_gl::windo..: Using default platform
2020-12-22 13:22:08.940 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: ViewRootImpl >> surfaceChanged W=1200, H=2000)
2020-12-22 13:22:08.940 2937-2937/rust.quad_android V/ndk_glue: WindowResized
2020-12-22 13:22:08.947 2937-2937/rust.quad_android V/ndk_glue: ContentRectChanged
2020-12-22 13:22:08.948 2937-2937/rust.quad_android V/ndk_glue: WindowRedrawNeeded
2020-12-22 13:22:08.950 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2020-12-22 13:22:08.951 2937-2937/rust.quad_android D/InputMethodManager: prepareNavigationBarInfo() DecorView@5b6f8a7[NativeActivity]
2020-12-22 13:22:08.951 2937-2937/rust.quad_android D/InputMethodManager: getNavigationBarColor() -855310
2020-12-22 13:22:08.951 2937-2937/rust.quad_android V/ndk_glue: WindowHasFocus
2020-12-22 13:22:08.956 2937-2937/rust.quad_android D/InputMethodManager: prepareNavigationBarInfo() DecorView@5b6f8a7[NativeActivity]
2020-12-22 13:22:08.956 2937-2937/rust.quad_android D/InputMethodManager: getNavigationBarColor() -855310
2020-12-22 13:22:08.957 2937-2937/rust.quad_android V/InputMethodManager: Starting input: tba=rust.quad_android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-12-22 13:22:08.957 2937-4294/rust.quad_android I/gfx_backend_gl::windo..: Display vendor "Android", version (1, 4), extensions: "EGL_KHR_get_all_proc_addresses EGL_ANDROID_presentation_time EGL_KHR_swap_buffers_with_damage EGL_ANDROID_get_native_client_buffer EGL_ANDROID_front_buffer_auto_refresh EGL_ANDROID_get_frame_timestamps EGL_EXT_surface_SMPTE2086_metadata EGL_EXT_surface_CTA861_3_metadata EGL_EXT_gl_colorspace_bt2020_linear EGL_EXT_gl_colorspace_bt2020_pq EGL_KHR_image EGL_KHR_image_base EGL_EXT_image_gl_colorspace EGL_KHR_gl_colorspace EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_fence_sync EGL_KHR_create_context EGL_KHR_config_attribs EGL_KHR_surfaceless_context EGL_EXT_create_context_robustness EGL_ANDROID_image_native_buffer EGL_KHR_wait_sync EGL_ANDROID_recordable EGL_KHR_partial_update EGL_EXT_pixel_format_float EGL_KHR_mutable_render_buffer EGL_IMG_context_priority EGL_KHR_no_config_context "
2020-12-22 13:22:08.957 2937-2937/rust.quad_android D/InputMethodManager: startInputInner - Id : 0
2020-12-22 13:22:08.957 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: Configurations:
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1404
2020-12-22 13:22:08.958 2937-2937/rust.quad_android I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android I/chatty: uid=10251(rust.quad_android) identical 1 line
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android I/chatty: uid=10251(rust.quad_android) identical 1 line
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1
2020-12-22 13:22:08.958 2937-4294/rust.quad_android I/chatty: uid=10251(rust.quad_android) identical 2 lines
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android I/chatty: uid=10251(rust.quad_android) identical 4 lines
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x44, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.958 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x44, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1405
2020-12-22 13:22:08.959 2937-4294/rust.quad_android V/gfx_backend_gl::windo..: 	CONFORMANT=0x45, RENDERABLE=0x45, NATIVE_RENDERABLE=0x0, SURFACE_TYPE=0x1
2020-12-22 13:22:08.959 2937-4294/rust.quad_android W/gfx_backend_gl::windo..: no compatible EGL config found, trying off-screen
2020-12-22 13:22:08.966 2937-4294/rust.quad_android I/mali_winsys: new_window_surface() [1200x2000] return: 0x3000
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/glow::native: glow!
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/gfx_backend_gl::windo..: glActiveShaderProgram
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/khronos_egl: glActiveShaderProgram
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/gfx_backend_gl::windo..: glActiveTexture
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/khronos_egl: glActiveTexture
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/gfx_backend_gl::windo..: glAttachShader
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/khronos_egl: glAttachShader
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/gfx_backend_gl::windo..: glBeginConditionalRender
2020-12-22 13:22:08.967 2937-4294/rust.quad_android W/khronos_egl: glBeginConditionalRender
2020-12-22 13:22:08.967 2937-4293/rust.quad_android I/RustStdoutStderr: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/backend/gl/src/window/egl.rs:204:49
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr: stack backtrace:
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr:    0:       0x7a6faf27fc - <unknown>
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr:    1:       0x7a6fb0c238 - <unknown>
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr:    2:       0x7a6faf006c - <unknown>
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr:    3:       0x7a6faf4574 - <unknown>
2020-12-22 13:22:08.968 2937-4293/rust.quad_android I/RustStdoutStderr:    4:       0x7a6faf40fc - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:    5:       0x7a6faf4c88 - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:    6:       0x7a6faf4800 - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:    7:       0x7a6faf2d50 - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:    8:       0x7a6faf4794 - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:    9:       0x7a6fb0a36c - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:   10:       0x7a6fb0a2f0 - <unknown>
2020-12-22 13:22:08.969 2937-4293/rust.quad_android I/RustStdoutStderr:   11:       0x7a6f931794 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   12:       0x7a6f8df070 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   13:       0x7a6f8edd80 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   14:       0x7a6f98ce28 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   15:       0x7a6f974d20 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   16:       0x7a6f972110 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   17:       0x7a6f937dd8 - <unknown>
2020-12-22 13:22:08.970 2937-4293/rust.quad_android I/RustStdoutStderr:   18:       0x7a6f8ed7b0 - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   19:       0x7a6f953c98 - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   20:       0x7a6f5ca560 - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   21:       0x7a6f8be2f0 - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   22:       0x7a6f8bf00c - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   23:       0x7a6f8caf00 - <unknown>
2020-12-22 13:22:08.971 2937-4293/rust.quad_android I/RustStdoutStderr:   24:       0x7a6f8c93d8 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   25:       0x7a6f8c6824 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   26:       0x7a6f8c6fc8 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   27:       0x7a6f8c66b0 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   28:       0x7a6f8c9480 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   29:       0x7a6f8cab44 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   30:       0x7a6f8c0448 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   31:       0x7a6faf6744 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   32:       0x7b052938e4 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   33:       0x7b05236040 - <unknown>
2020-12-22 13:22:08.972 2937-4293/rust.quad_android I/RustStdoutStderr:   34:                0x0 - <unknown>
2020-12-22 13:22:08.974 2937-2937/rust.quad_android D/InputMethodManager: prepareNavigationBarInfo() DecorView@5b6f8a7[NativeActivity]
2020-12-22 13:22:08.974 2937-2937/rust.quad_android D/InputMethodManager: getNavigationBarColor() -855310
2020-12-22 13:22:08.975 2937-2937/rust.quad_android V/InputMethodManager: Starting input: tba=rust.quad_android ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
2020-12-22 13:22:08.975 2937-2937/rust.quad_android D/InputMethodManager: startInputInner - Id : 0
2020-12-22 13:22:08.980 2937-4294/rust.quad_android I/mali_winsys: delete_surface() [1200x2000] return
2020-12-22 13:22:08.980 2937-4294/rust.quad_android W/libEGL: eglTerminate() called w/ 1 objects remaining
2020-12-22 13:22:08.980 2937-4294/rust.quad_android W/libEGL: EGLNativeWindowType 0x7a7b718010 disconnect failed
2020-12-22 13:22:09.010 2937-2937/rust.quad_android I/ViewRootImpl@41bb7f9[NativeActivity]: MSG_RESIZED: frame=(0,0,1200,2000) ci=(0,0,0,23) vi=(0,0,0,23) or=1
```

Looks like glow related error. glBeginConditionalRender only avalible for [OpenGL (not ES)](https://docs.gl/gl4/glBeginConditionalRender)

### PR DESCRIPTION
**Pull request by Gordon-F**
Fixes #3550

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends: OpenGL ES

### CODE REVIEW

File: src/backend/gl/src/window/egl.rs [hunk 1]
```diff
@@ -217,16 +225,23 @@ impl hal::Instance<crate::Backend> for Instance {
         };
         let attributes = [
             egl::RENDER_BUFFER as usize,
-            egl::SINGLE_BUFFER as usize,
```
Comment (Gordon-F) [inline src/backend/gl/src/window/egl.rs:220]: With `SINGLE_BUFFER` only black window is displayed

File: src/backend/gl/src/window/egl.rs [hunk 2]
```diff
@@ -142,7 +142,12 @@ impl hal::Instance<crate::Backend> for Instance {
             Ok(Some(config)) => config,
             Ok(None) => {
                 log::warn!("no compatible EGL config found, trying off-screen");
-                supports_native_window = false;
+                // Android surface still presentable
+                supports_native_window = if cfg!(target_os = "android") {
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:146]: This seems rather concerning. Which of the `config_attributes` does Android not like, to start with?

File: src/backend/gl/src/window/egl.rs [hunk 3]
```diff
@@ -194,7 +199,10 @@ impl hal::Instance<crate::Backend> for Instance {
             .unwrap();
         let context = unsafe {
             glow::Context::from_loader_function(|name| {
-                self.egl.get_proc_address(name).unwrap() as *const _
+                match self.egl.get_proc_address(name) {
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:202]: nit: use `.map_or(ptr::null(), |p| p as *const _)`

File: src/backend/gl/src/window/egl.rs [hunk 4]
```diff
@@ -163,7 +168,7 @@ impl hal::Instance<crate::Backend> for Instance {
             egl::CONTEXT_CLIENT_VERSION,
             3, // Request GLES 3.0 or higher
         ];
-        if cfg!(debug_assertions) && wsi_library.is_none() {
+        if cfg!(debug_assertions) && wsi_library.is_none() && cfg!(not(target_os = "android")) {
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:171]: would be easier to write `!cfg!(target_os = "android")`

File: src/backend/gl/src/window/egl.rs (hunk 1 above)
Comment (kvark) [reply src/backend/gl/src/window/egl.rs:220]: Can we make this conditional? Something like `if cfg!(target_os = "android") { ... } else { ... }`

File: src/backend/gl/src/window/egl.rs [hunk 5]
```diff
@@ -217,16 +225,23 @@ impl hal::Instance<crate::Backend> for Instance {
...
+            egl::BACK_BUFFER as usize,
             // Always enable sRGB
             egl::GL_COLORSPACE as usize,
             egl::GL_COLORSPACE_SRGB as usize,
             egl::ATTRIB_NONE,
         ];
+
+        let native_window_ptr = match has_handle.raw_window_handle() {
+            #[cfg(target_os = "android")]
+            Rwh::Android(_) => native_window as *mut _ as _,
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:237]: interestingly, there is similar code in the Wayland PR, so this would need to be merged upon rebase

**Review by kvark — COMMENTED** [review]
Thank you for the PR! I'm excited to see Android GL support coming ❤️

File: src/backend/gl/src/window/egl.rs (hunk 2 above)
Comment (Gordon-F) [reply src/backend/gl/src/window/egl.rs:236]: I'll try to figure it out later

File: src/backend/gl/src/window/egl.rs [hunk 6]
```diff
@@ -88,6 +99,70 @@ fn test_wayland_display() -> Option<libloading::Library> {
...
+    let client_extensions = egl
+        .query_string(None, egl::EXTENSIONS)
+        .map_err(|_| hal::UnsupportedBackend)?
+        .to_string_lossy();
+    log::info!("Client extensions: {:?}", client_extensions);
+    let client_ext_list = client_extensions.split_whitespace().collect::<Vec<_>>();
+
+    let mut wsi_library = None;
+
+    let wayland_display = if client_ext_list.contains(&"EGL_EXT_platform_wayland") {
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:116]: could you provide the `client_ext_list` you get on Android? Does it even have those extensions? If it doesn't there is no need to gate this as `not(target_os = "android")`

Comment (kvark) [reply src/backend/gl/src/window/egl.rs:116]: It would  be much better to have a run-time switch instead of the compile-time switch

File: src/backend/gl/src/window/egl.rs [hunk 7]
```diff
@@ -364,32 +410,59 @@ impl hal::Instance<crate::Backend> for Instance {
         attributes.push(egl::ATTRIB_NONE);
 
         let native_window_ptr = match has_handle.raw_window_handle() {
+            #[cfg(target_os = "android")]
+            Rwh::Android(_) => native_window as *mut _ as _,
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:414]: why do we even need `native_window` produced in the first match, given that it's only used here in that second match over the same thing? It looks to me that there should only be one match, but we can follow-up separately...

File: src/backend/gl/src/window/egl.rs (hunk 6 above)
Comment (Gordon-F) [reply src/backend/gl/src/window/egl.rs:116]: Are X11 or Wayland supports Android?

Query string with EGL_NO_DISPLAY is supported only if the EGL version is 1.5 or greater (Android 10+, < 10% devices).

Also we can get default display and make something like this:
```rust
let default_display = egl.get_display(egl::DEFAULT_DISPLAY).map_err(|_| hal::UnsupportedBackend)?;
let client_extensions = egl
    .query_string(Some(default_display), egl::EXTENSIONS)
    .map_err(|_| hal::UnsupportedBackend)?
    .to_string_lossy();
let client_ext_list = client_extensions.split_whitespace().collect::<Vec<_>>();

let wayland_display = if client_ext_list.contains(&"EGL_EXT_platform_wayland") {
    //...
}

let x11_display = if client_ext_list.contains(&"EGL_EXT_platform_x11") { 
    //...
}

display = if let Some(library) = wayland_display { 
    //...
}

display = if let Some(library) = x11_display { 
    //...
}
```

Comment (kvark) [reply src/backend/gl/src/window/egl.rs:116]: I just want to minimize the code behind the feature gates, since it's more difficult to keep working.
For example, if `EGL_EXT_platform_wayland` and `EGL_EXT_platform_x11` are never exposed on Android anyway, there is no harm to have the code checking for them.

Comment (Gordon-F) [reply src/backend/gl/src/window/egl.rs:116]: Worked example without feature gates. But with some performance cost, because we should initialize default display and get client extension:

```rust
let default_display = egl.get_display(egl::DEFAULT_DISPLAY).ok_or_else(|| {
    log::warn!("Unable to get default display");
    hal::UnsupportedBackend
})?;

egl.initialize(default_display).map_err(|_| hal::UnsupportedBackend)?;

// Query string with EGL_NO_DISPLAY is supported only if the EGL version is 1.5 or greater
let client_extensions = egl
    .query_string(Some(default_display), egl::EXTENSIONS)
    .map_err(|_| hal::UnsupportedBackend)?
    .to_string_lossy();
log::info!("Client extensions: {:?}", client_extensions);
let client_ext_list = client_extensions.split_whitespace().collect::<Vec<_>>();

egl.terminate(default_display).map_err(|_| hal::UnsupportedBackend)?;

let mut wsi_library = None;

let wayland_display = if client_ext_list.contains(&"EGL_EXT_platform_wayland") {
    test_wayland_display()
} else {
    None
};

let x11_display = if client_ext_list.contains(&"EGL_EXT_platform_x11") {
    open_x_display()
} else {
    None
};
```

Comment (kvark) [reply src/backend/gl/src/window/egl.rs:116]: These are different extensions. See:
> If display is EGL_NO_DISPLAY, then the EGL_EXTENSIONS string describes the set of supported client extensions. If display is a valid, initialized display, then the EGL_EXTENSIONS string describes the set of display extensions supported by that display. The set of supported client extensions is disjoint from the set of extensions supported by any given display. 

So the current code does it correctly. It doesn't however take into account that requirement for 1.5 EGL version. I don't know how we could do that, even, since we at this early point we don't know anything about the version. I think we should just check the error code and proceed without client extensions (i.e. empty list?..) if that fails without considering the backend unavailable.

Comment (Gordon-F) [reply src/backend/gl/src/window/egl.rs]: > These are different extensions

TIL. Fixed.

File: src/backend/gl/src/window/egl.rs [hunk 8]
```diff
@@ -364,32 +378,59 @@ impl hal::Instance<crate::Backend> for Instance {
...
+            }
+        } else {
+            let attributes_i32: Vec<i32> = attributes.iter().map(|a| (*a as i32).into()).collect();
+            match inner.egl.create_window_surface(
+                inner.display,
+                inner.config,
+                native_window_ptr,
+                Some(&attributes_i32),
+            ) {
+                Ok(raw) => Ok(Surface {
```
Comment (kvark) [inline src/backend/gl/src/window/egl.rs:421]: can we move this out from if/else? Something like
```rust
let (raw, wl_window) = if inner.version >= (1, 5) { } else { };
Ok(Surface {
})
```

**Review by kvark — COMMENTED** [review]
We are almost there!
Please check the review notes and squash the commits.

File: src/backend/gl/src/window/egl.rs [hunk 9]
```diff
@@ -225,22 +228,23 @@ impl hal::Instance<crate::Backend> for Instance {
...
+        let client_ext_str = match client_extensions {
+            Ok(ext) => ext.to_string_lossy().into_owned(),
+            Err(_) => String::new(),
+        };
+        log::info!("Client extensions: {:?}", client_ext_str);
 
         let mut wsi_library = None;
 
-        let wayland_display = if client_ext_list.contains(&"EGL_EXT_platform_wayland") {
+        let wayland_display = if client_ext_str.contains(&"EGL_EXT_platform_wayland") {
```
[the remark this answers is not in the document]
Comment (Gordon-F) [reply src/backend/gl/src/window/egl.rs:241]: Previously, we cast from `String` to `Vec<String>` and use only for extensions checking. Why we can't use `contains` with String?

[the remark this answers is not in the document]
Comment (kvark) [reply src/backend/gl/src/window/egl.rs:241]: We can, but arguably it's a messier approach

**Review by kvark — APPROVED** [review]
Thank you!
bors r+
