### PR TITLE
[mtl] Expose version check

### LINKED ISSUE #2342: Quad example segfault on OS X 10.11.6
Short info header:
- GFX version: git log
commit 14820d33a0b8e0363f78aae6df71d1bc60b9f367
Merge: 393d657 4e22939

- OS: OS X El Capitan Version 10.11.6 MacBoox Pro Retina 13-inch Early 2015
- GPU: Intel Iris Graphics 6100 1536 MB

I have an attached external 4K monitor via HDMI if that matters.

Crash message as follows:
AdapterInfo { name: "Intel(R) Iris(TM) Graphics 6100", vendor: 0, device: 0, software_rendering: false }
Memory types: [MemoryType { properties: DEVICE_LOCAL, heap_index: 0 }, MemoryType { properties: COHERENT | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE, heap_index: 1 }, MemoryType { properties: DEVICE_LOCAL | CPU_VISIBLE | CPU_CACHED, heap_index: 1 }]
2018-08-24 18:10:16.168 quad[83247:133187848] -[MTLSamplerDescriptorInternal setLodAverage:]: unrecognized selector sent to instance 0x7fa8c248d730
Segmentation fault: 11

### PR DESCRIPTION
**Pull request by grovesNL**
Partial fix for #2342 (probably need some more version checks, but I have no simple way to check)
Also fixes the MSL version check for macOS versions beyond (technically `(11, 0)` would've failed)

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [X] tested examples with the following backends: Metal
- [ ] `rustfmt` run on changed code

### CODE REVIEW

File: src/backend/metal/src/lib.rs [hunk 1]
```diff
@@ -366,6 +368,17 @@ struct PrivateCapabilities {
     max_texture_size: u64,
 }
 
+impl PrivateCapabilities {
+    fn version_at_least(major: u32, minor: u32, needed_major: u32, needed_minor: u32) -> bool {
```
Comment (grovesNL) [inline src/backend/metal/src/lib.rs]: Not sure if this is the best place to put these, open to other ideas
