### PR TITLE
[vk] extend dual-source blending disable on Intel/windows

### LINKED ISSUE #1930: [vk] crash in dual-source blending on Windows + Intel
Short info header:
- GFX version: HAL master
- OS: Windows
- GPU: Intel HD Graphics 630

Linked issues:
  - https://software.intel.com/en-us/forums/graphics-driver-bug-reporting/topic/748226
  - https://github.com/szeged/webrender/issues/136
  - https://github.com/hrydgard/ppsspp/issues/10074
  - https://bugs.dolphin-emu.org/issues/10470

We need to:
  ~~1. confirm if it's the intel driver bug, check if a fix is coming (in which case we can wait)~~
  2. start black-listing some OS/driver/HW for specific features. This is unfortunate, but we'll get more exceptions like this in the long run, so we might as well start here.

### PR DESCRIPTION
**Pull request by zakorgy**
This is a follow up on #1931 and fixes #1930.
cc @kvark 

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends: vulkan
- [ ] `rustfmt` run on changed code

---
This change is [Reviewable](https://reviewable.io/reviews/gfx-rs/gfx/2488)

### CODE REVIEW

File: src/backend/vulkan/src/lib.rs [hunk 1]
```diff
@@ -557,6 +557,11 @@ impl hal::PhysicalDevice<Backend> for PhysicalDevice {
             && self.properties.device_id & info::intel::DEVICE_KABY_LAKE_MASK
                 == info::intel::DEVICE_KABY_LAKE_MASK;
 
+        let is_windows_intel_sky = cfg!(windows)
```
Comment (kvark) [inline src/backend/vulkan/src/lib.rs]: let's have a single boolean for this workaround, e.g. `is_windows_intel_dual_src_bug`
