### PR TITLE
[pre-ll] Add emscripten build failure workaround

### LINKED ISSUE #2721: [pre-ll] Calling `Factory::create_pipeline_state_raw` causes emscripten to fail to build.
Short info header:
- GFX version: 0.18.0
- OS: Emscripten, building on Windows

I'm trying to build a `gfx`/`winit` app (pre-ll) on the web, but am having trouble with building with emscripten. I've narrowed my problem down to calling `create_pipeline_state_raw` on `Factory`, but am having trouble with understanding the actual problem (`llc.exe` fails with `-1073740940`, which is heap corruption?). I'm unsure what the exact question here is other than asking for advice on how to resolve this? (Perhaps a version of emscripten known to work well?) Thanks!

Below is a minimal repro I've created.

```rust
// [dependencies]
// winit = "0.19.0"
// gfx = "0.18.0"
// glutin = "0.20.0"
// gfx_device_gl = "0.16.0"
// gfx_window_glutin = "0.30.0"

use gfx;
use gfx::gfx_defines;
use gfx::gfx_pipeline;
use gfx::gfx_pipeline_inner;
use gfx::traits::FactoryExt;

type Cf = gfx::format::Rgba8;
type Df = gfx::format::DepthStencil;

gfx_defines! {
    pipeline noop {
        out: gfx::RenderTarget<Cf> = "Target0",
    }
}

fn main() {
    let events_loop = winit::EventsLoop::new();
    let window = winit::WindowBuilder::new();

    let context =  glutin::ContextBuilder::new()
            .with_gl(glutin::GlRequest::Specific(glutin::Api::WebGl, (2, 0)));

    let (_, _, mut factory, _, _) =
        gfx_window_glutin::init::<Cf, Df>(window, context, &events_loop).unwrap();

    // If this is commented out, the build succeeds.
    dbg!(factory
        .create_pipeline_simple(&[], &[], noop::new())
        .unwrap());
}
```

Calling `cargo web build` with emscripten `sdk-1.38.30-64bit` and a `Web.toml` of:
```
# default-target = "wasm32-unknown-emscripten" # makes no difference
default-target = "asmjs-unknown-emscripten"

[cargo-web]
minimum-version = "0.6.0"

[target.emscripten]
link-args = ["-s", "USE_SDL=2"]
```

Outputs a very large error:
```
   Compiling emscripten-winit-gfx-test v0.1.0 ($PROJECT_DIR)
error: linking with `emcc.bat` failed: exit code: 1
  |
  = note: "cmd" "/c" "emcc.bat" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.16mpeuxpinc54dyl.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1aclwulshthpq5dv.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1dkelm6tomus2tav.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1klznyjsrmdntkeq.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1ltvrmwc8bun4yib.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1miqzxxmdrlxu4x9.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1o2q11piwqekhxv8.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1pmogkqprkn06sll.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1srs1rhryzpg2x0f.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1sy1by7ssmkwsgwd.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1t942npdwsv3j1cb.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.1uyeevis68wgvu8b.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.23ttbjdcn1vc2h86.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.28mlkbo2rxo3hrga.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.2krxdmfaktsqf5iq.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.37izsty4nhrn9o48.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3bb23nkj8s3jtc7.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3glfkhasjcj6vupr.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3hlbt94t8zs9cgcj.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3k5hlcwha2hair77.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3lco90w8r4qjezs1.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3nhrig3zp123oq9o.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3othld82cuy1yzui.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3q161sz7j5rk2dv4.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.3rkugq07qeyn46l7.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.40hhgkdyg36bvpcd.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.4izsmtjy233p0py.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.4jazgmhnmag42cp4.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.4wju15zgduyzz29n.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.4wye8pcmzlkt2ajj.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.58kexot3x518s41p.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.5ja7d895v26w08l.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.bh3uzoz18isxxmk.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.dks9vpsjw5we2u8.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.msjtd8mx181mhj0.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.nx36fwof9z3m92c.rcgu.o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.ssevugjc2ecvgr7.rcgu.o" "-o" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"_rust_eh_personality\"]" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\emscripten_winit_gfx_test-dd10bed5847aa5e9.4ni68kiokea2e7k6.rcgu.o" "-O0" "--memory-init-file" "0" "-g4" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps" "-L" "$PROJECT_DIR\\target\\debug\\deps" "-L" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libgfx_window_glutin-cc98dcc7f0a570dd.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libgfx_device_gl-2cb6933abc8c1edf.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libgfx_gl-2a503a34ba5f7ab6.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libglutin-64052346ef784f8b.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libwinit-fd5a6797cba29fd8.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\liblibc-8492f3ad567a8898.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\liblazy_static-55ec61886960eb65.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libgfx-e70d6115f52887fd.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libgfx_core-2ab61ca1365afeda.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libdraw_state-7005873241889e56.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libbitflags-8c06d61774cb4214.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\liblog-6649671ff33435d5.rlib" "$PROJECT_DIR\\target\\asmjs-unknown-emscripten\\debug\\deps\\libcfg_if-94ccff70135b7c89.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libstd-af9362ed5d81a840.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libpanic_unwind-4d55a38564aae54a.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libbacktrace_sys-f8521075e248b627.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libunwind-7c91ffdc8da860d3.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\librustc_demangle-0ad27b9879d551d3.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liblibc-588f18eae3ea58be.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\liballoc-4ebf5caee903d98f.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\librustc_std_workspace_core-8895b32baedb08c6.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcore-6a9d233d01acc350.rlib" "$HOME\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\asmjs-unknown-emscripten\\lib\\libcompiler_builtins-851bb3b5f6c4db49.rlib" "-l" "c" "-s" "NO_EXIT_RUNTIME=1" "-s" "ALLOW_MEMORY_GROWTH=0" "-s" "USE_SDL=2" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1" "-s" "ABORTING_MALLOC=0" "-s" "WASM=0"
  = note: shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\rust.metadata.bin is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.0.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.1.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.10.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.11.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.12.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_2xauer_archive_contents\gfx_window_glutin-cc98dcc7f0a570dd.gfx_window_glutin.3m4ykmox-cgu.13.rcgu.bc.z is not valid according to llvm-nm, cannot link
          [many more lines like this]
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp__hmtav_archive_contents\rust.metadata.bin is not a valid object file for emscripten, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp__hmtav_archive_contents\core-6a9d233d01acc350.core.8myysa1f-cgu.0.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_yfnmhv_archive_contents\rust.metadata.bin is not a valid object file for emscripten, cannot link
          shared:WARNING: object $HOME\appdata\local\temp\emscripten_temp_yfnmhv_archive_contents\compiler_builtins-851bb3b5f6c4db49.compiler_builtins.397dg3ty-cgu.0.rcgu.bc.z is not valid according to llvm-nm, cannot link
          shared:ERROR: '$EMSDK_DIR/clang/e1.38.30_64bit\llc.exe $HOME\AppData\Local\Temp\emscripten_temp_wqvom8\emscripten_winit_gfx_test-dd10bed5847aa5e9.bc -march=js -filetype=asm -o $HOME\AppData\Local\Temp\tmpexgcmt.4.js -emscripten-stack-size=5242880 -O0 -emscripten-assertions=1 -emscripten-no-aliasing-function-pointers -emscripten-global-base=8 -enable-emscripten-cpp-exceptions -emscripten-no-exit-runtime' failed (-1073740940)


error: Could not compile `emscripten-winit-gfx-test`.
```

### PR DESCRIPTION
**Pull request by tangmi**
Fixes #2721.

PR checklist:
- [x] tested examples with the following backends: macOS/GL
- [x] `rustfmt` run on changed code

### CODE REVIEW

File: src/backend/gl/src/factory.rs [hunk 1]
```diff
@@ -392,6 +392,13 @@ impl f::Factory<R> for Factory {
         let mut inputs = [None; d::MAX_VERTEX_ATTRIBUTES];
         for i in 0 .. d::MAX_VERTEX_ATTRIBUTES {
             inputs[i] = desc.attributes[i].map(|at| BufferElement {
+                // Note: this `Option::unwrap` call fails the emscripten (sdk-1.38.16-64bit) build. Inlining the call seems to work around the issue. (See #2721)
+                #[cfg(target_os = "emscripten")]
+                desc: match desc.vertex_buffers[at.0 as usize] {
```
Comment (kvark) [inline src/backend/gl/src/factory.rs]: should we just do this for all targets unconditionally? (with the comment preserved, of course)

Comment (tangmi) [reply src/backend/gl/src/factory.rs]: I'm unsure. I'm personally a fan of keeping hacks as closely scope to their specific condition, but I think the style is a decision of the project, so I'll defer to you. I'm happy to make the change, if you'd like.

**Comment by tangmi** [comment]
@grovesNL has asked for a minimal repro for this emscripten issue, which I'll try and get when I have more time.
