### PR TITLE
[mtl] cubemap blit support

### LINKED ISSUE #2363: metal: Can't upload small mip levels for BC-compressed textures via vkCmdCopyBufferToImage
Given a texture that's, say, 4x4 and uses BC1 and has 3 mip levels (4x4, 2x2, 1x1), uploading mip levels requires copies that have the extents 2x2 and 1x1 for smaller mip levels.

When using vkCmdCopyBufferToImage with appropriately set up imageExtent, I get the following panic:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
 left: `2`,
right: `0`', /Users/travis/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/4a1b551/src/backend/metal/src/command.rs:1132:5
stack backtrace:
  0:        0x12d2eefaf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hed04c7a1477ef1e3
  1:        0x12d2e375d - std::sys_common::backtrace::print::h336400f22676933f
  2:        0x12d2f15e3 - std::panicking::default_hook::{{closure}}::h0d6700a02d682978
  3:        0x12d2f136c - std::panicking::default_hook::h90363c6d6ac04260
  4:        0x12d2f1cdb - std::panicking::rust_panic_with_hook::h81c4f3add25e6667
  5:        0x12d2f1aae - std::panicking::continue_panic_fmt::hfa057b7c1de88179
  6:        0x12d2f1a00 - std::panicking::begin_panic_fmt::hd1123702300ea9f2
  7:        0x12cf15862 - gfx_backend_metal::command::div::h8276b6195d7ad202
  8:        0x12cf1590a - gfx_backend_metal::command::compute_pitches::h6e05ac3c5cd5700e
  9:        0x12cf18858 - gfx_backend_metal::command::exec_blit::hcfc548f16b81ec4e
 10:        0x12cc9daaf - gfx_backend_metal::command::CommandSink::blit_commands::he2ced2d08b18a042
 11:        0x12cc98dc5 - <gfx_backend_metal::command::CommandBuffer as gfx_hal::command::raw::RawCommandBuffer<gfx_backend_metal::Backend>>::copy_buffer_to_image::hd0ae44ffe9a05385
 12:        0x12ccb14ea - portability_gfx::impls::gfxCmdCopyBufferToImage::hcb4ff4d6d389a30d
 13:        0x1006b1beb - _ZN3RBX8Graphics13TextureVulkan13commitChangesEv
 14:        0x10074d44f - _ZN3RBX8GraphicsL13uploadTextureEPNS0_6DeviceERKNS0_5ImageERKNS_9ContentIdE
 15:        0x10074cdcc - _ZN3RBX8Graphics14TextureManager22processPendingRequestsEv
 16:        0x100781853 - _ZN3RBX8Graphics10RenderView17renderPerformImplEdPNS0_11FramebufferENS_10RenderTypeE
 17:        0x10003c773 - _ZN15RenderScheduler18renderIntoViewBaseEv
 18:        0x10027b013 - _ZN11QOgreWidget5eventEP6QEvent
 19:        0x10721fb9e - _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
 20:        0x107221272 - _ZN12QApplication6notifyEP7QObjectP6QEvent
 21:        0x1000fa4ba - _ZN17RobloxApplication6notifyEP7QObjectP6QEvent
 22:        0x106dbd4c3 - _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
 23:        0x106dbe51a - _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData
 24:        0x10ce33846 - _ZN28QCocoaEventDispatcherPrivate19processPostedEventsEv
 25:        0x10ce34130 - _ZN28QCocoaEventDispatcherPrivate26postedEventsSourceCallbackEPv
 26:     0x7fff2d303a10 - __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
 27:     0x7fff2d3bd42b - __CFRunLoopDoSource0
 28:     0x7fff2d2e646f - __CFRunLoopDoSources0
 29:     0x7fff2d2e58ec - __CFRunLoopRun
 30:     0x7fff2d2e5152 - CFRunLoopRunSpecific
 31:     0x7fff2c5cfd95 - RunCurrentEventLoopInMode
 32:     0x7fff2c5cfa0e - ReceiveNextEventCommon
 33:     0x7fff2c5cf883 - _BlockUntilNextEventMatchingListInModeWithFilter
 34:     0x7fff2a880a72 - _DPSNextEvent
 35:     0x7fff2b016e33 - -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
 36:     0x7fff2a875884 - -[NSApplication run]
 37:        0x10ce32eff - _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
 38:        0x106db97a0 - _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
 39:        0x106dbdb36 - _ZN16QCoreApplication4execEv
 40:        0x1003f9f15 - main
```

The issue is that compute_pitches assumes that region size is divisible by block size which presumably is 4x4 - but this is *not* true for mip levels that are smaller than 4x4. In general you can make textures that have dimensions that aren't divisible by 4 and use BCn formats - pitch has to be computed by rounding the dimensions up after division.

### LINKED ISSUE #2364: metal: Can't generate mipmaps for cubemaps using vkCmdBlitImage because it's not implemented
We use vkCmdBlitImage to do progressive blitting from mip 0 to mip 1 to mip 2 etc., including cubemaps. Getting this panic:

```
thread '<unnamed>' panicked at 'not yet implemented', /Users/travis/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/4a1b551/src/backend/metal/src/internal.rs:382:30
stack backtrace:
  0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
  1: std::sys_common::backtrace::print
  2: std::panicking::default_hook::{{closure}}
  3: std::panicking::default_hook
  4: std::panicking::rust_panic_with_hook
  5: std::panicking::begin_panic
  6: gfx_backend_metal::internal::ImageBlitPipes::create
  7: gfx_backend_metal::internal::ImageBlitPipes::get::{{closure}}
  8: <storage_map::StorageMap<L, std::collections::hash::map::HashMap<K, V, S>>>::get_or_create_with
  9: gfx_backend_metal::internal::ImageBlitPipes::get
 10: <gfx_backend_metal::command::CommandBuffer as gfx_hal::command::raw::RawCommandBuffer<gfx_backend_metal::Backend>>::blit_image
 11: portability_gfx::impls::gfxCmdBlitImage
 12: _ZN3RBX8Graphics19DeviceContextVulkan15generateMipmapsEPNS0_7TextureE
 13: _ZN3RBX8Graphics6EnvMap10fullUpdateEPNS0_13DeviceContextE
 14: _ZN3RBX8Graphics12SceneManager11renderBeginEPNS0_13DeviceContextEjjRKNS0_12RenderCameraE
 15: _ZN3RBX8Graphics12SceneManager11renderSceneEPNS0_13DeviceContextEPNS0_11FramebufferERKNS0_12RenderCameraE
 16: _ZN3RBX8Graphics10RenderView17renderPerformImplEdPNS0_11FramebufferENS_10RenderTypeE
 17: _ZN15RenderScheduler18renderIntoViewBaseEv
 18: _ZN11QOgreWidget5eventEP6QEvent
 19: _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
 20: _ZN12QApplication6notifyEP7QObjectP6QEvent
 21: _ZN17RobloxApplication6notifyEP7QObjectP6QEvent
 22: _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
 23: _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData
 24: _ZN28QCocoaEventDispatcherPrivate19processPostedEventsEv
 25: _ZN28QCocoaEventDispatcherPrivate26postedEventsSourceCallbackEPv
 26: __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
 27: __CFRunLoopDoSource0
 28: __CFRunLoopDoSources0
 29: __CFRunLoopRun
 30: CFRunLoopRunSpecific
 31: RunCurrentEventLoopInMode
 32: ReceiveNextEventCommon
 33: _BlockUntilNextEventMatchingListInModeWithFilter
 34: _DPSNextEvent
 35: -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
 36: -[NSApplication run]
 37: _ZN21QCocoaEventDispatcher13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
 38: _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
 39: _ZN16QCoreApplication4execEv
 40: main
```

Presumably due to this: https://github.com/gfx-rs/gfx/blob/b2b3f8a8d629556504ed3200f7d894a908fc7380/src/backend/metal/src/internal.rs#L381-L382

### PR DESCRIPTION
**Pull request by kvark**
Fixes #2363
Fixes #2364
... supposedly, since I haven't tested it manually, and CTS doesn't bother setting the cube compatible bit. I filed an internal issue about that to Khronos.

PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [ ] tested examples with the following backends:
- [ ] `rustfmt` run on changed code

### CODE REVIEW

File: src/backend/metal/src/native.rs [hunk 1]
```diff
@@ -356,6 +356,27 @@ impl Image {
...
+                Some(self.raw.new_texture_view_from_slice(
+                    self.mtl_format,
+                    metal::MTLTextureType::D2Array,
+                    NSRange {
+                        location: 0,
+                        length: self.raw.mipmap_level_count(),
+                    },
+                    NSRange {
+                        location: 0,
+                        length: self.kind.num_layers() as _,
```
Comment (grovesNL) [inline src/backend/metal/src/native.rs]: Do we need `* 6` here? Or where else do we account for for the number of faces?

**Comment by kvark** [comment]
The kind is 2D so 6 multiplier shiuld already be there.

**Comment by grovesNL** [comment]
Ok, if the multiplier is already handled then it seems fine to me – would be nice to test with an example though
