### PR TITLE
[ll] Heap types and device capabilities

### LINKED ISSUE #1379: Allocating heap memory for low level DX12 backend fails
When attempting to compile and run the trianglell example on Windows 10 64 bit MSVC with the default DX12 backend, the program panics at runtime with the following message:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2147024809`', src\backend\dx12ll\src\factory.rs:215:8
```
The [create_heap function](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12ll/src/factory.rs#L215) asserts that
```
assert_eq!(winapi::S_OK, unsafe {
            self.inner.CreateHeap(&desc, &dxguid::IID_ID3D12Heap, &mut heap)
        });
```
Commenting this out, the example simply fails to run without providing a backtrace.
```
error: process didn't exit successfully: `target\debug\examples\trianglell.exe` (exit code: 2173)
```
The example works fine compiled with with `--features vulkan`.

### PR DESCRIPTION
**Pull request by kvark**
Fixes #1379
Closes #1381

### CODE REVIEW

File: src/corell/src/lib.rs [hunk 1]
```diff
@@ -123,6 +135,8 @@ pub struct Device<R: Resources, F: Factory<R>, Q: CommandQueue> {
     pub transfer_queues: Vec<TransferQueue<Q>>,
     pub heap_types: Vec<HeapType>,
     pub memory_heaps: Vec<u64>,
+    /// Device capabilities
+    pub caps: Capabilities,
```
Comment (msiglreith) [inline src/corell/src/lib.rs]: Could we already have access to these capabilities from `Adapter`?
So users could have more control about which device to open beside the current `AdapterInfo`.

Comment (kvark) [inline src/corell/src/lib.rs]: That was my original design, but unfortunately D3D12 only queries those via `D3D12Device`, which we only get in `open()`, so I had to move stuff under `Device`. Anyhow, I'll be happy to revise this later.
