### PR TITLE
Fix #1602

### LINKED ISSUE #1602: SDL throwing BadMatch with proprietary Nvidia driver on Linux
Requesting a specific OpenGL version when using SDL and the proprietary Nvidia driver on Linux causes this error to be thrown:
```
Could not make GL context current: BadMatch (invalid parameter attributes)
```
Removing the lines setting the GL version solves the problem with Nvidia, but causes Intel to not be able to understand 3.2 shaders. The problem seems to also be solved for Nvidia when removing the following line from `gfx_window_sdl/lib.rs`:
```rust
attr.set_alpha_size(cf.0.get_alpha_stencil_bits());
```
This however causes my Intel machine to display colors incorrectly.

### PR DESCRIPTION
**Pull request by magnonellie**
Setting GL attributes before creating the window fixes #1602. That did however require getting a reference to the video subsystem earlier, hence the new function signatures.

### CODE REVIEW

File: src/window/sdl/src/lib.rs [hunk 1]
```diff
@@ -90,48 +90,52 @@ pub type InitOk<Cf, Df> =
...
-        format: sdl2_pixel_format_from_gfx(cf)
-                    .ok_or(InitError::PixelFormatUnsupportedError)?,
-        ..window.display_mode()?
-    };
-    window.set_display_mode((Some(display_mode)))?;
     {
         let depth_total_bits = df.0.get_total_bits();
         let stencil_bits = df.0.get_alpha_stencil_bits();
-        let attr = window.subsystem().gl_attr();
+        let attr = video_subsystem.gl_attr();
```
Comment (kvark) [inline src/window/sdl/src/lib.rs]: I don't understand. Isn't `window.subsystem()` exactly the same thing here as `video_subsystem`?

Comment (magnonellie) [reply src/window/sdl/src/lib.rs]: It is, but the problem is that if you get the subsystem through the window, you have to have already created the window before setting the attributes which is what caused the problem to begin with. :sweat:

Comment (kvark) [reply src/window/sdl/src/lib.rs]: Ah I see now. You moved the `let mut window = builder.opengl().build()?;` below.

**Comment by kvark** [comment]
Thank you!
bors r+
