### PR TITLE
[WebGL] Fix index buffer usage

### LINKED ISSUE #3669: [GL] Rebind buffer to another target panic on WebGL
```log
WebGL: INVALID_OPERATION: bindBuffer: buffers bound to non ELEMENT_ARRAY_BUFFER targets can not be bound to ELEMENT_ARRAY_BUFFER target

panicked at 'Error InvalidOperation executing command: BindIndexBuffer(WebBufferKey(2v1))', gfx/src/backend/gl/src/queue.rs:1072:13
```

From [WebGL docs](https://developer.mozilla.org/ru/docs/Web/API/WebGLRenderingContext/bindBuffer): 
```
Only one target can be bound to a given WebGLBuffer. An attempt to bind the buffer to another target will throw an INVALID_OPERATION error and the current buffer binding will remain the same.
```

[SpectorJS](https://github.com/BabylonJS/Spector.js) trace: 
```log
viewport: 0, 0, 0, 0
depthRange: 0, 1
scissor: 0, 0, 0, 0
bindBuffer: ELEMENT_ARRAY_BUFFER, undefined
viewport: 0, 0, 0, 0
depthRange: 0, 1
scissor: 0, 0, 0, 0
bindBuffer: ELEMENT_ARRAY_BUFFER, undefined
viewport: 0, 0, 0, 0
depthRange: 0, 1
scissor: 0, 0, 0, 0
bindFramebuffer: DRAW_FRAMEBUFFER, WebGLFramebuffer - ID: 2
framebufferRenderbuffer: DRAW_FRAMEBUFFER, COLOR_ATTACHMENT0_WEBGL, RENDERBUFFER, WebGLRenderbuffer - ID: 0
getError
drawBuffers: [..(1)..]
getError
colorMask: true, true, true, true
getError
clearBufferfv: COLOR, 0, [..(4)..]
getError
scissor: 0, 0, 2048, 1536
getError
viewport: 0, 0, 2048, 1536
depthRange: 0, 1
getError
useProgram: WebGLProgram - ID: 0
getError
disable: BLEND
getError
colorMask: true, true, true, true
getError
frontFace: CCW
disable: CULL_FACE
lineWidth: 1
disable: POLYGON_OFFSET_FILL
getError
disable: DEPTH_TEST
getError
depthMask: true
getError
bindBuffer: ELEMENT_ARRAY_BUFFER, WebGLBuffer - ID: 1
getError -> INVALID_OPERATION
bindBuffer: ARRAY_BUFFER, WebGLBuffer - ID: 1
vertexAttribPointer: 0, 3, FLOAT, false, 24, 0
vertexAttribDivisor: 0, 0
enableVertexAttribArray: 0
bindBuffer: ARRAY_BUFFER, undefined
getError
bindBuffer: ARRAY_BUFFER, WebGLBuffer - ID: 1
vertexAttribPointer: 1, 3, FLOAT, false, 24, 12
vertexAttribDivisor: 1, 0
enableVertexAttribArray: 1
bindBuffer: ARRAY_BUFFER, undefined
getError
drawElements: TRIANGLES, 9, UNSIGNED_SHORT, 1024VertexFragment
getError -> INVALID_OPERATION
fenceSync: SYNC_GPU_COMMANDS_COMPLETE, 0 -> WebGLSync - ID: 360
getSyncParameter: WebGLSync - ID: 359, SYNC_STATUS -> SIGNALED
deleteSync: WebGLSync - ID: 359
bindFramebuffer: DRAW_FRAMEBUFFER, undefined
bindFramebuffer: READ_FRAMEBUFFER, WebGLFramebuffer - ID: 1
blitFramebuffer: 0, 0, 2048, 1536, 0, 0, 2048, 1536, COLOR_BUFFER_BIT, NEAREST
bindFramebuffer: READ_FRAMEBUFFER, undefined
```

Note: Error was found with code from https://github.com/gfx-rs/gfx/pull/3668

### PR DESCRIPTION
**Pull request by Gordon-F**
Fixes #3669
PR checklist:
- [ ] `make` succeeds (on *nix)
- [ ] `make reftests` succeeds
- [x] tested examples with the following backends: WebGL/OpenGL

Currently, the problem is not fully resolved:
image

### CODE REVIEW

**Comment by kvark** [comment]
At least the index buffer works now? 🎉

**Comment by Gordon-F** [comment]
> At least the index buffer works now?

Yes, now we can allocate an index buffer and send data to it. But I don't know why this buffer also used for other data even if it doesn't have `Usage::TRANSFER_SRC` flag.

**Comment by Gordon-F** [comment]
@kvark Texture problem seems unrelated to buffer usage. I'm trying to investigate what's wrong. Anyway index buffer fix should be ready to merge.

File: src/backend/gl/src/command.rs [hunk 1]
```diff
@@ -115,7 +114,7 @@ pub enum Command {
     SetBlendSlot(ColorSlot, Option<pso::BlendState>),
     BindAttribute(n::AttributeDesc, n::RawBuffer, i32, u32),
     //UnbindAttribute(n::AttributeDesc),
-    CopyBufferToBuffer(n::RawBuffer, n::RawBuffer, command::BufferCopy),
+    CopyBufferToBuffer(n::RawBuffer, n::RawBuffer, u32, u32, command::BufferCopy),
```
Comment (kvark) [inline src/backend/gl/src/command.rs:117]: note for the future: we should refactor this an other variants to have named fields. A bare number is too ambiguous.

File: src/backend/gl/src/device.rs [hunk 2]
```diff
@@ -1310,13 +1317,14 @@ impl d::Device<B> for Device {
             n::Buffer::Unbound { size, .. } => size,
             n::Buffer::Bound { .. } => panic!("Unexpected Buffer::Bound"),
         };
+        let mem_buffer = memory
```
Comment (kvark) [inline src/backend/gl/src/device.rs:1320]: can we match here instead of accessing `.0` and `.1` later on?

File: src/backend/gl/src/native.rs [hunk 3]
```diff
@@ -40,15 +40,20 @@ pub enum Buffer {
...
         buffer: RawBuffer,
         range: Range<buffer::Offset>,
+        target: u32,
     },
 }
 
 impl Buffer {
     // Asserts that the buffer is bound and returns the raw gl buffer along with its sub-range.
-    pub(crate) fn as_bound(&self) -> (RawBuffer, Range<u64>) {
+    pub(crate) fn as_bound(&self) -> (RawBuffer, Range<u64>, u32) {
```
Comment (kvark) [inline src/backend/gl/src/native.rs:49]: should probably make a structure for this now...

File: src/backend/gl/src/device.rs [hunk 4]
```diff
@@ -233,10 +233,11 @@ impl Device {
                 gl.use_program(Some(program));
             }
             for (name, &(register, slot)) in name_binding_map.iter() {
+                log::trace!("Get binding {:?} from program {:?}", name, program);
```
Comment (kvark) [inline src/backend/gl/src/device.rs:236]: nit: the backend currently imports the macros from `log`, so it can be just `trace!` here.
At the end of the day, I'd prefer all the code to use the style you used here with fully-qualified log, but it's not very important to fix.

File: src/backend/gl/src/queue.rs [hunk 5]
```diff
@@ -616,19 +616,44 @@ impl Queue {
...
                 self.share.context.DisableVertexAttribArray(attribute.location);
             }*/
-            com::Command::CopyBufferToBuffer(src, dst, ref r) => unsafe {
+            com::Command::CopyBufferToBuffer(src, dst, _src_target, dst_target, ref r) => unsafe {
+                let is_index_buffer_only_element_dst =
+                    !self.share.private_caps.index_buffer_role_change
+                        && dst_target == glow::ELEMENT_ARRAY_BUFFER;
+
+                let copy_src_target = glow::COPY_READ_BUFFER;
+                let copy_dst_target = if is_index_buffer_only_element_dst {
```
Comment (kvark) [inline src/backend/gl/src/queue.rs:625]: why not just use the `dst_target` directly?

**Review by kvark — COMMENTED** [review]
Looks great!
A few nits I commented are not too important.
One question in the end is perhaps good to resolve before merging.

File: src/backend/gl/src/command.rs (hunk 1 above)
Comment (Gordon-F) [reply src/backend/gl/src/command.rs]: Fixed this one, and added `TODO` to fix others.

File: src/backend/gl/src/device.rs (hunk 4 above)
Comment (Gordon-F) [reply src/backend/gl/src/device.rs:236]: Fixed in separate commit. I'm also prefer `log::` style.

File: src/backend/gl/src/queue.rs (hunk 5 above)
Comment (Gordon-F) [reply src/backend/gl/src/queue.rs:632]: Moved comment higher 

`// WebGL not allowed to copy data from other targets to element buffer and can't copy element data to other buffers`

**Review by kvark — APPROVED** [review]
Thank you, this is high quality code!
bors r+

**Comment by kvark** [comment]
Still CI errors

**Comment by Gordon-F** [comment]
> Still CI errors

Sorry, should be fixed now! But looks like CI is stuck 🤔
